### ISSUE TITLE
dependencies and compilations instructions missing 

### ISSUE THREAD

**Issue by shirishag75** [farcodev/farcolony#5]
there need to be dependencies and compilations instructions, both of which are missing. 

Also would the following command work in getting something that is compilable ?

```
git clone https://github.com/farcodev/farcolony.git --depth=1 
```

Look forward to know.

**Comment by farcodev** [comment]
FARC use a non-free third party component suite (TMS), so the code is provided as is w/o compilation directives. 
It is more for knowledge purpose that the source code is available, I don't provide support for compilation sorry.

FYI it uses the following free components; GLScene (an old version of it), FastMM, BASS, GR32, GTTimerDemo, Imaging, oxLibs3DS, and two bits of code components found on the dead Borland Community forums.
